# -*- coding: utf-8 -*-
"""Cities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4XYh6eVaYMvsXOGMFameqnajFp_EhBD
"""

!pip install -q -U google-genai numpy

import os
import numpy as np

from google import genai
from google.genai import types
from google.colab import userdata

GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")

client = genai.Client(
    api_key=GOOGLE_API_KEY
)

print("Gemini connected.")

from google.colab import files

uploaded = files.upload()

with open("cities.txt", "r", encoding="utf-8") as file:
    text = file.read()

print(text[:500000])

def chunk_text(text, chunk_size=80, overlap=20):

    words = text.split()

    chunks = []

    start = 0

    while start < len(words):

        end = start + chunk_size

        chunk = " ".join(words[start:end])

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

chunks = chunk_text(
    text,
    chunk_size=80,
    overlap=20
)

print("Total chunks:", len(chunks))

for i, chunk in enumerate(chunks):

    print(f"\nChunk {i+1}")
    print("-" * 60)

    print(chunk)

EMBEDDING_MODEL = "gemini-embedding-001"


def create_embedding(
    text,
    task_type="RETRIEVAL_DOCUMENT"
):

    response = client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=text,
        config=types.EmbedContentConfig(
            task_type=task_type,
            output_dimensionality=768
        )
    )

    return np.array(
        response.embeddings[0].values,
        dtype=np.float32
    )

vector_store = []


for i, chunk in enumerate(chunks):

    print(
        f"Creating embedding for chunk {i+1}"
    )

    embedding = create_embedding(
        chunk,
        task_type="RETRIEVAL_DOCUMENT"
    )

    vector_store.append({
        "chunk_id": i + 1,
        "text": chunk,
        "embedding": embedding
    })


print("\nVector store created.")
print("Total vectors:", len(vector_store))

def retrieve(query, top_k=3):

    # Create embedding for the user question
    query_embedding = create_embedding(
        query,
        task_type="RETRIEVAL_QUERY"
    )

    results = []

    # Compare question with every stored chunk
    for chunk in vector_store:

        score = cosine_similarity(
            query_embedding,
            chunk["embedding"]
        )

        results.append({
            "chunk_id": chunk["chunk_id"],
            "text": chunk["text"],
            "score": float(score)
        })

    # Highest similarity first
    results.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return results[:top_k]

retrieve(
    "Which city has Burj Khalifa?"
)

question = "Which city has the Colosseum?"

results = retrieve(question)

print(results)

GENERATION_MODEL = "gemini-2.5-flash"


def ask_rag(question, top_k=3):

    # ============================
    # RETRIEVE
    # ============================

    retrieved_chunks = retrieve(
        question,
        top_k=top_k
    )


    # ============================
    # BUILD CONTEXT
    # ============================

    context = "\n\n".join([
        f"""
Chunk ID: {chunk['chunk_id']}

{chunk['text']}
"""
        for chunk in retrieved_chunks
    ])


    # ============================
    # PROMPT
    # ============================

    prompt = f"""
You are a city information assistant.

Answer the user's question using ONLY
the information provided in the retrieved
context.

Do not use outside knowledge.

If the answer is not available, say:

"I don't have enough information in the knowledge base."

=========================
CONTEXT
=========================

{context}

=========================
QUESTION
=========================

{question}

=========================
ANSWER
=========================
"""


    # ============================
    # GENERATE
    # ============================

    response = client.models.generate_content(
        model=GENERATION_MODEL,
        contents=prompt
    )


    return {
        "answer": response.text,
        "sources": retrieved_chunks
    }

result = retrieve(
    "Which city has the Colosseum?"
)

print(type(result))
print(result)

for item in result:
    print(item.keys())